name: run-engine

on:

  workflow_dispatch:


jobs:

  run:

    runs-on: ubuntu-latest


    env:

      DART_API_KEY: ${{ secrets.DART_API_KEY }}

      KIS_APP_KEY: ${{ secrets.KIS_APP_KEY }}

      KIS_APP_SECRET: ${{ secrets.KIS_APP_SECRET }}



    steps:


      - name: Checkout

        uses: actions/checkout@v4



      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"



      # 기존 KIS 토큰 복원

      - name: Restore KIS token

        uses: actions/cache@v4

        with:

          path: kis_token.json

          key: kis-token-cache-v1



      - name: Install

        run: |

          pip install -r requirements.txt



      - name: Run python

        run: |

          python main.py



      # 실행 중 새로 생성된 토큰 저장

      - name: Save KIS token

        uses: actions/cache/save@v4

        with:

          path: kis_token.json

          key: kis-token-cache-v1
